# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [4]:
print(np.__version__)

1.18.1


#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
d = np.zeros(10)
print(d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [16]:
print("{} bytes".format(d.size * d.itemsize))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [123]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [31]:
z = np.arange(10,49,1)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


# 8.  Reverse a vector (first element becomes last) (★☆☆)

In [43]:
z[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [40]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [13]:
import numpy as np
t = np.array([1,2,0,0,4,0])
c = t!=0
for i in range(c.size):
    if(c[i]==True):
        print(i)

0
1
4


#### 11. Create a 3x3 identity matrix (★☆☆)

In [44]:
f = np.eye(3,3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12. Create a 3x3x3 array with random values (★☆☆)

In [53]:
h = np.random.randint(1,50,size = (3,3,3))
print(h)

[[[ 6  3  1]
  [ 9 10 30]
  [11 12 37]]

 [[43 31 45]
  [46 13 36]
  [40 48 41]]

 [[49 15 33]
  [ 4 43  9]
  [18 46  3]]]


#### 13. Create a 10x10 array with randomvalues and find the minimum and maximum values (★☆☆)

In [15]:
arr = np.random.randint(0,150,size = (10,10))
print(arr)
print("max value is {} & min value is {}".format(np.max(arr),np.min(arr)) )

[[ 36 138 137  39  37  32  40  79  77 121]
 [ 34 101   5 106  80  88  79   4  27  89]
 [100  57 122  54  68   8 142  38  27  81]
 [ 97  95  33  37  49  58 133  65 103  43]
 [ 13  82   8 121  98 112  54 140  42  40]
 [ 11  80   5 139  27  64 134  70 132  29]
 [ 34  37 138 115  72 126  60  77   1 105]
 [ 69  23 120  80 102  71  78  69  87 145]
 [ 61  87 113 129 149   6  44   3  55   9]
 [ 96  69 137 113   8  11  18  37  96  65]]
max value is 149 & min value is 1


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [20]:
vec = np.random.rand(30)
print(np.mean(vec))

0.4279283486453771


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [41]:
import numpy as np 
a = np.zeros((4,5))
print(a)
np.pad(a, pad_width = 1,mode = 'constant',constant_values = 1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [43]:
w = np.random.randint(-10,10,size =(4,4))
print(w)
np.pad(w, pad_width = 1, mode = 'constant')
#default paddin g value is 0

[[ -8  -7  -5   1]
 [  9   8  -3   4]
 [  4  -8   0   8]
 [-10  -9 -10   2]]


array([[  0,   0,   0,   0,   0,   0],
       [  0,  -8,  -7,  -5,   1,   0],
       [  0,   9,   8,  -3,   4,   0],
       [  0,   4,  -8,   0,   8,   0],
       [  0, -10,  -9, -10,   2,   0],
       [  0,   0,   0,   0,   0,   0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [11]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [23]:
import random
d = np.zeros((5,5))
for i in range(5):
    for j in range(5):
        if(i>j):
            d[i][j]= random.randint(1,4)
print(d)

[[0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [4. 3. 0. 0. 0.]
 [1. 1. 2. 0. 0.]
 [3. 3. 2. 1. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [38]:
# let 0 represent blzck and 1 represent white 
check = np.ones((8,8))
for i in range(8):
    for j in range(8):
        if((i+j)%2 == 0):
            check[i][j]= 0;
print(check)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [73]:
arr = np.random.randint(1,10,size=(6,7,8))
n = 100
x = int(n/arr[0].size)
y = int((n-((x)*arr[0].size))/(arr[0][0].size))
z = int((n-((x)*arr[0].size)) - ((y)*arr[0][0].size))
print("index = ({},{},{})".format(x,y,z))

index = (1,5,4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [75]:
arr = np.eye(2)
rep = (4,4)
print(np.tile(arr,rep))

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [76]:
m = np.random.random((5,5))
mi, ma = m.min(), m.max()
m = (m - mi)/(ma - mi)
print(m)

[[0.88669921 0.12644211 0.56739842 0.46861464 0.75820484]
 [0.31330608 0.50356643 0.23682654 0.37388596 0.26484365]
 [0.84713686 0.99089746 0.25035959 0.6824115  0.74246767]
 [0.         0.51442433 0.55347437 0.05895771 0.6767574 ]
 [0.45341929 0.02345666 1.         0.54070312 0.15825323]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [145]:
color_desc = ([ ("R",ubyte,1),("G", ubyte,1),("B", ubyte,1),("A",ubyte,1)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [77]:
m1 = np.random.randint(1,15,size = (5,3))
m2 = np.random.randint(1,6,size = (3,2))
print(m1.dot(m2))

[[32 67]
 [63 79]
 [19 36]
 [39 44]
 [37 33]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
#given array be n
for i in range(n.size):
    if(n[i]<8 and n[i]>3):
        n[i] = 0
print(n)

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
# output will be 
9 # sum of 0,1,2,3,4 and -1
10 # sum of above nos but -1 is axis (last axis)

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)


Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [93]:
#last one is invalid rest all are valid

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [4]:
#nan
#0
#[-9.22337204e+18] a very large value

#### 29. How to round away from zero a float array ? (★☆☆)

In [7]:
v = np.array( [1.6,2.0,3.7,4.8,4.4,0.8,9.7,.24,5.5,6.93])
v = np.ceil(v)
print(v)

[ 2.  2.  4.  5.  5.  1. 10.  1.  6.  7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [142]:
ar1 = np.array([1,2,3,4,5,6])
ar2 = np.array([2,4,6,8])
ar3 = np.intersect1d(ar1,ar2)
print(ar3)

[2 4 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [144]:
#defaults = np.seterr(all="ignore")
#Z = np.ones(1) / 0
#print(Z)

[inf]


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [109]:
#no it is false
#as np.sqrt(-1) reutrns nan whilw np.emath.sqrt(-1) returns 1j(complex  no.)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [110]:
y_day = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",y_day)
t_day     = np.datetime64('today', 'D')
print("Today: ",t_day)
tom  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tom)

Yestraday:  2020-04-28
Today:  2020-04-29
Tomorrow:  2020-04-30


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [115]:
july_2016 = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [76]:
A = np.ones(3)*1
#print(A)
B = np.ones(3)*2
#print(B)
C = np.ones(3)*3
#print(C)
print(np.add(A,B,out=A))
np.divide(A,2,out=A)
print(np.negative(A, out =A))
print(np.multiply(A,B,out=A))
#stores the results in A ensured by A

[3. 3. 3.]
[-1.5 -1.5 -1.5]
[-3. -3. -3.]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [60]:
E = np.random.uniform(0,20,5)
print(E)
#1 
print(E.astype(int),)
#2
print(np.floor(E))
#3
print(np.ceil(E) -1)
#4
print(E - E%1)# subtracts the dcimalpart from each element
#5
print(np.trunc(E))

[ 4.20411952  6.64079609 17.34851928 11.12930343 11.44562077]
[ 4  6 17 11 11]
[ 4.  6. 17. 11. 11.]
[ 4.  6. 17. 11. 11.]
[ 4.  6. 17. 11. 11.]
[ 4.  6. 17. 11. 11.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [55]:
v = np.zeros((5,5))
v = v + np.arange(5) 
print(v)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [119]:
def generator():
    for i in range(10):
        return random.randint(1,10)
li =[];
for i in range(10):
    li.append(generator())
qw = np.array(li)
print(qw)

[6 9 7 4 1 9 5 8 2 1]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [117]:
ve = np.random.random(10)
print(ve)

[0.67496911 0.90714251 0.15629251 0.2266105  0.53691161 0.7130603
 0.96326533 0.45711973 0.18164578 0.48522642]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [46]:
import numpy as np
vector = np.random.randint(-20,20,size =10)
print("orignal vector :",vector)
np.sort(vector)

orignal vector : [-20  18   0 -20  16 -18  -3  -8  15  -7]


array([-20, -20, -18,  -8,  -7,  -3,   0,  15,  16,  18])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [53]:
Z = np.random.randint(1,20,size = (10))
print(Z)
z = np.add.reduce(Z)
print(z)

[ 2  5  8 13  5  2 12 13  5 11]
76


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [139]:
x1,y1 = random.randint(1,10),random.randint(1,10)
A = np.random.random((x1,y1))
x2, y2 = random.randint(1,10),random.randint(1,10)
B = np.random.randint((x2,y2))
if(np.array_equal(A,B)):
    print("equal")
else:
    print("not equal")

not equal


#### 43. Make an array immutable (read-only) (★★☆)

In [121]:
a = np.zeros(15)
a.flags.writeable = False
a[1] = 3 # error generating statement

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [51]:
cart = np.random.random((10,2))
x = cart[:,0]
y = cart[:,1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan(y/x)
print(cart)
print(r,"\n\n\n",theta)

[[0.6695088  0.10928312]
 [0.93988317 0.36567144]
 [0.41099551 0.00358896]
 [0.08900094 0.99500957]
 [0.61630561 0.1441158 ]
 [0.57758739 0.849771  ]
 [0.44002628 0.10668092]
 [0.94970397 0.65806628]
 [0.58468981 0.14565226]
 [0.77659447 0.9782761 ]]
[0.67836925 1.00851176 0.41101118 0.99898209 0.63293125 1.02748136
 0.45277361 1.15541718 0.60255851 1.24904888] 


 [0.16180188 0.37104037 0.00873215 1.48158642 0.2297107  0.97382641
 0.23785284 0.60595662 0.24414113 0.89982293]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [49]:
vctr = np.random.randint(0,10,size = 10)
print(vctr)
v = np.max(vctr)
for i in range(vctr.size):
    if(vctr[i]==v):
        vctr[i]=0
print(vctr)

[2 8 6 6 7 4 2 3 1 2]
[2 0 6 6 7 4 2 3 1 2]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [34]:
x = np.linspace(0,1,10)
y = np.linspace(0,1,10)
dtypef = [("X" , np.float64),("Y",np.float64)]
z = np.zeros((10,10),dtype = dtypef)
z["X"],z["Y"] = np.meshgrid(x,y)
print(z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [131]:
x = np.random.randint(-10,10,size = 5)
y = np.random.randint(-10,10,size = 5)
C = 1/np.subtract.outer(x,y)
print(C)

[[ 0.14285714  0.33333333  0.09090909  0.07142857  0.07692308]
 [-0.5        -0.16666667  0.5         0.2         0.25      ]
 [ 0.5        -0.5         0.16666667  0.11111111  0.125     ]
 [ 0.125       0.25        0.08333333  0.06666667  0.07142857]
 [ 0.16666667  0.5         0.1         0.07692308  0.08333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [141]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [105]:
arr = np.random.randint(-5,5,size =10)
for i in arr:
    print(i, end = '      ')

2      4      2      0      -5      -5      -4      2      -5      3      

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [102]:
n= int(input("enter a scalar"))
ar = np.random.randint(1,50,size =10)
print(ar)
dif = abs(ar[0]- n)
holder =ar[0]
for i in ar:
    if(abs(i - n)<dif):
        dif = abs((i-n)) 
        holder = i
print("closest value = ", holder)

enter a scalar34
[14 16 22 33 12 32 45 43 20 27]
closest value =  33


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)